# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 373403e5fed56e27d66b17c677ae12886d9edee95f56830243e7610d98de9fcdaf786452d3cf5201816d1a8ee2a164b585b9d12bccbaa1ccf267526061548955

test:
  secret_key_base: fa80c41eafa4440e1bfd334b8dcf15ce429ceb2886ca3c420ac7b8ef82fe5212ad069cead5cf3c47c1cfcb12416d4a7fdf0418fa38916828b2179181e3e5eba5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
